### ISSUE TITLE
no version

### ISSUE THREAD

**Issue by tqf6** [Websoft9/ansible-mongodb#3]
**Describe the bug**

## Deployment method

- [x] subscription image from MarketPlace of Cloud
- [ ] All-in-one Installer
- [ ] ansible-playbook cli
- [ ] mcloud
- [ ] create instance from private image

## Bug source

- [x] Bugs from installation 
- [ ] Bugs from first use
- [ ] Other (You should describe it)   

## System Environment

**Application Version**

e.g v4.5

**OS**

- [ ] Ubuntu18.x
- [ ] Ubuntu20.x
- [x] CentOS7.x
- [ ] CentOS8.x
- [ ] AmazonLinux2
- [ ] OracleLinux7.8
- [ ] OracleLinux8.2
- [ ] Other (You should describe it) 

**Cloud PlatForm**

- [ ] Azure
- [ ] Aws
- [ ] 阿里云
- [ ] 腾讯云
- [ ] 华为云
- [ ] AlibabaCloud
- [x] HUWEICloud
- [ ] Other (You should describe it) 

### Bug Context

Bug context includes bug error, error logs and service status, it is very important for resolving issue

```
# bug error
"MongoDB shell version v4.0.24",
        "Docker version 20.10.6, build 370c289",
        "adminmongo version:",
        "System version: CentOS 7.9",
        "Image name: ansible-mongodb"

# service status 
(paste here) 

# error logs
(paste here) 
```

### Bug Screenshot
![image](https://user-images.githubusercontent.com/83911329/119431567-6633dc80-bd45-11eb-9f4c-7e2755bf488a.png)

## Your suggestion

**The reason of Bug**

You can describe the reason if you have found it

**Your solution for Bug**

You can describe your solution here

**Additional context**

You can add any other context about the problem here.

**Comment by zengxc-1996** [comment]
tested aliyun centos 7 

is OK

    "end_check_versions.stdout_lines": [
        "MongoDB shell version v3.4.24",
        "Docker version 20.10.6, build 370c289",
        "adminmongo version: \"version\": \"0.0.23\",",
        "System version: CentOS 7.9",
        "Image name: mongodbzengxc-CentOS7.9"
    ]
